server:
  port: 8668

spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://dpg-cqjsqmmehbks73ci4m5g-a.oregon-postgres.render.com:5432/db_r8pq
    jdbc-url: jdbc:postgresql://dpg-cqjsqmmehbks73ci4m5g-a.oregon-postgres.render.com:5432/db_r8pq
    username: db_r8pq_user
    password: 2kMi8rZTd2UeGczLUaU7Q9MmYBZFkHsn
    driver-class-name: org.postgresql.Driver
    configuration:
      jdbc-url: jdbc:postgresql://dpg-cqjsqmmehbks73ci4m5g-a.oregon-postgres.render.com:5432/db_r8pq
      username: db_r8pq_user
      password: 2kMi8rZTd2UeGczLUaU7Q9MmYBZFkHsn
  liquibase:
    enabled: true
    url: jdbc:postgresql://dpg-cqjsqmmehbks73ci4m5g-a.oregon-postgres.render.com:5432/db_r8pq
    user: db_r8pq_user
    password: 2kMi8rZTd2UeGczLUaU7Q9MmYBZFkHsn
    change-log: classpath:db/changelog/changeLogs.xml

  servlet:
    multipart:
      max-request-size: 10MB

languages:
  primaryLang: 'en'

attach:
  upload:
    folder: '/resources/static/image/'

service:
  sms-service:
    username: 'samandarshodmonov1998@gmail.com'
    password: 'TaEotaLMYaUqqGTgTrzjGnmIFo7whQfaf82vMU8o'
    url: 'https://notify.eskiz.uz'
